//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjBusReservationWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public int Id { get; set; }
        public Nullable<int> OTP1 { get; set; }
        public Nullable<int> Registration_Id { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
